// flow-typed signature: 83c474ee2a305f0d688b37b86bd528f2
// flow-typed version: <<STUB>>/babel-plugin-transform-exponentiation-operator_v^6.8.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-exponentiation-operator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-exponentiation-operator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-exponentiation-operator/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-exponentiation-operator/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-exponentiation-operator/lib/index'>;
}
