// flow-typed signature: f0ec43d871f131ce69b6eef7d5d51105
// flow-typed version: <<STUB>>/babel-helper-plugin-test-runner_v^6.18.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-helper-plugin-test-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-helper-plugin-test-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-helper-plugin-test-runner/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-helper-plugin-test-runner/lib/index.js' {
  declare module.exports: $Exports<'babel-helper-plugin-test-runner/lib/index'>;
}
