// flow-typed signature: 3a7392b2e73f076c2542a02f3b939a77
// flow-typed version: <<STUB>>/babel-plugin-transform-es2015-duplicate-keys_v^6.6.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-es2015-duplicate-keys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-es2015-duplicate-keys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-es2015-duplicate-keys/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-es2015-duplicate-keys/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-es2015-duplicate-keys/lib/index'>;
}
