// flow-typed signature: 47e82521a558621285396fd190964705
// flow-typed version: <<STUB>>/compat-table_vkangax/compat-table#688097f1ce623cb113640cc9108fe04fc418b823/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compat-table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'compat-table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compat-table/build' {
  declare module.exports: any;
}

declare module 'compat-table/data-es2016plus' {
  declare module.exports: any;
}

declare module 'compat-table/data-es5' {
  declare module.exports: any;
}

declare module 'compat-table/data-es6' {
  declare module.exports: any;
}

declare module 'compat-table/data-esintl' {
  declare module.exports: any;
}

declare module 'compat-table/data-esnext' {
  declare module.exports: any;
}

declare module 'compat-table/data-non-standard' {
  declare module.exports: any;
}

declare module 'compat-table/esnext-browsers' {
  declare module.exports: any;
}

declare module 'compat-table/jquery.floatThead.min' {
  declare module.exports: any;
}

declare module 'compat-table/master' {
  declare module.exports: any;
}

declare module 'compat-table/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compat-table/build.js' {
  declare module.exports: $Exports<'compat-table/build'>;
}
declare module 'compat-table/data-es2016plus.js' {
  declare module.exports: $Exports<'compat-table/data-es2016plus'>;
}
declare module 'compat-table/data-es5.js' {
  declare module.exports: $Exports<'compat-table/data-es5'>;
}
declare module 'compat-table/data-es6.js' {
  declare module.exports: $Exports<'compat-table/data-es6'>;
}
declare module 'compat-table/data-esintl.js' {
  declare module.exports: $Exports<'compat-table/data-esintl'>;
}
declare module 'compat-table/data-esnext.js' {
  declare module.exports: $Exports<'compat-table/data-esnext'>;
}
declare module 'compat-table/data-non-standard.js' {
  declare module.exports: $Exports<'compat-table/data-non-standard'>;
}
declare module 'compat-table/esnext-browsers.js' {
  declare module.exports: $Exports<'compat-table/esnext-browsers'>;
}
declare module 'compat-table/jquery.floatThead.min.js' {
  declare module.exports: $Exports<'compat-table/jquery.floatThead.min'>;
}
declare module 'compat-table/master.js' {
  declare module.exports: $Exports<'compat-table/master'>;
}
declare module 'compat-table/node.js' {
  declare module.exports: $Exports<'compat-table/node'>;
}
