// flow-typed signature: 247fe43638a6cb7ea4b034d4ca5ea418
// flow-typed version: <<STUB>>/electron-to-chromium_v^1.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-to-chromium'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-to-chromium' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-to-chromium/automated-update' {
  declare module.exports: any;
}

declare module 'electron-to-chromium/build' {
  declare module.exports: any;
}

declare module 'electron-to-chromium/full-versions' {
  declare module.exports: any;
}

declare module 'electron-to-chromium/versions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-to-chromium/automated-update.js' {
  declare module.exports: $Exports<'electron-to-chromium/automated-update'>;
}
declare module 'electron-to-chromium/build.js' {
  declare module.exports: $Exports<'electron-to-chromium/build'>;
}
declare module 'electron-to-chromium/full-versions.js' {
  declare module.exports: $Exports<'electron-to-chromium/full-versions'>;
}
declare module 'electron-to-chromium/index' {
  declare module.exports: $Exports<'electron-to-chromium'>;
}
declare module 'electron-to-chromium/index.js' {
  declare module.exports: $Exports<'electron-to-chromium'>;
}
declare module 'electron-to-chromium/versions.js' {
  declare module.exports: $Exports<'electron-to-chromium/versions'>;
}
